#!/bin/bash

GIT_PROJECT_ROOT=$(git rev-parse --show-toplevel)
cd "$($GIT_PROJECT_ROOT "$0")"
docker build -f ./pre-commit.Dockerfile -t pre-commit . && docker run --rm --name pre-commit-run-{{cookiecutter.project_slug}} -v pre-commit:/.cache/pre-commit:delegated -v $(pwd)/:/sourcecode pre-commit
